spring:
  profiles:
    active: local
  main:
    web-application-type: none

mybatis:
  type-aliases-package: com.bin.push.mybatis.base.model
  mapper-locations: classpath:/mapper/*.xml
  check-config-location: true
  config-location: classpath:mysql-mybatis-config.xml